#!/usr/bin/python

import os
import sys
import doctest
import argparse
import importlib


def import_module(filename):
    if os.path.exists(filename) or '/' in filename:
        sys.path.append(os.getcwd())
        module_name = os.path.splitext(filename)[0].replace('/', '.')
    else:
        module_name = filename
    return importlib.import_module(module_name)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('module', type=import_module)
    args = parser.parse_args()
    e, n = doctest.testmod(args.module)
    if e:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
